version: "3.7"

services:
  pab:
    image: "pab:latest"
    build:
      context: .
      dockerfile: /src/main/resource/docker/Dockerfile
    container_name: pab
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bible
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: bible
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@algamish.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

  flyway:
    image: boxfuse/flyway
    container_name: "flyway"
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    command: -url=jdbc:postgresql://db:5432/bible -user=admin -password=admin -connectRetries=60 migrate
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:
