version: "3.8"

services:
  pab:
    image: "pab:latest"
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: pab
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
    restart: always

  mongo_db:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db-pab:/var/lib/mongo/data

volumes:
  db-pab:
